theme: jekyll-theme-hacker
title: Jijo Derick Abraham
description: UQIDAR Ph.D. student.
show_downloads: True
google_analytics:
#remote_theme: pages-themes/hacker@v0.2.0
#plugins:
#- jekyll-remote-theme
